name: pid1_trailmate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  geolocator: ^13.0.1
  image_picker: ^1.2.1
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  connectivity_plus: ^7.1.1
  shared_preferences: ^2.5.5
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true