// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzRLdsXuDFT8tXwYHkhRfcNQXIfydyNDc',
    appId: '1:186947429433:web:b024b53c6c4ca5514019e8',
    messagingSenderId: '186947429433',
    projectId: 'trailmate-ceda6',
    authDomain: 'trailmate-ceda6.firebaseapp.com',
    storageBucket: 'trailmate-ceda6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-O77exRzfh2jxJlyKs0tvFNyhlzRIIZY',
    appId: '1:186947429433:android:c1fcb29f86acf06a4019e8',
    messagingSenderId: '186947429433',
    projectId: 'trailmate-ceda6',
    storageBucket: 'trailmate-ceda6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmcxec8hgG4WiROt7dliFphuOwG6VCgbs',
    appId: '1:186947429433:ios:a1373b011e7d41bf4019e8',
    messagingSenderId: '186947429433',
    projectId: 'trailmate-ceda6',
    storageBucket: 'trailmate-ceda6.firebasestorage.app',
    iosClientId: '186947429433-161u452ou11n3lf1fv23nu80a4nqm4bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.pid1Trailmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzRLdsXuDFT8tXwYHkhRfcNQXIfydyNDc',
    appId: '1:186947429433:web:fd85bb342d70d21b4019e8',
    messagingSenderId: '186947429433',
    projectId: 'trailmate-ceda6',
    authDomain: 'trailmate-ceda6.firebaseapp.com',
    storageBucket: 'trailmate-ceda6.firebasestorage.app',
  );
}
